spring:
    application:
        name: config-server
    profiles:
        active: native
    
    cloud:
        config:
            server:
            #Local configuration: This location can either be of classpath or locations in the filesystem
                native:
                #Reads from a specific filesystem folder
                    search-locations: classpath:/config
server:
    port: 8071